import type {
  Task,
  Worker,
  GateCriteria,
  TokenSummary,
  CheckpointInfo,
  AuditEntry,
  GraphData,
} from "@/lib/mc/types";

export interface DemoState {
  stage: string;
  tasks: Task[];
  workers: Worker[];
  gates: Record<string, GateCriteria>;
  tokens: TokenSummary;
  checkpoints: CheckpointInfo[];
  audit: AuditEntry[];
  graph: GraphData | null;
}

export interface DemoStep {
  delay: number;
  type: "message" | "state";
  role?: "user" | "assistant";
  content?: string;
  patch?: Partial<DemoState>;
}

const INITIAL_STATE: DemoState = {
  stage: "discovery",
  tasks: [],
  workers: [],
  gates: {},
  tokens: {
    total_tokens: 0,
    total_cost: 0,
    budget_limit: 5.0,
    budget_used: 0,
    budget_remaining: 5.0,
    sessions: [],
  },
  checkpoints: [],
  audit: [],
  graph: null,
};

// Generate timestamps that look recent (offset in minutes from "now")
function ts(minutesAgo: number): string {
  return new Date(Date.now() - minutesAgo * 60_000).toISOString();
}

export const DEMO_SCRIPT: DemoStep[] = [
  // --- Opening ---
  {
    delay: 1000,
    type: "message",
    role: "assistant",
    content:
      "Hey! I'm Kai, your development coordinator. DutyBound is provenance-driven agentic project orchestration — AI agents that are bound by duty to follow process. Let me show you what that means.",
  },
  {
    delay: 2500,
    type: "message",
    role: "user",
    content: "I want to build a CLI task manager in Go",
  },
  {
    delay: 2000,
    type: "message",
    role: "assistant",
    content:
      "Great choice! DutyBound enforces a 10-stage gated workflow. I can't skip ahead — not even I, the orchestrator, can bypass the rules. We start at Discovery. Every task I create, every worker I spawn, gets logged in the audit trail.",
  },

  // --- Discovery stage begins ---
  {
    delay: 1500,
    type: "state",
    patch: {
      stage: "discovery",
      tasks: [
        {
          id: "t1",
          name: "Research CLI task managers",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "in_progress",
          worker_id: "w1",
          created_at: ts(5),
          updated_at: ts(5),
        },
        {
          id: "t2",
          name: "Analyze Go CLI frameworks",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "pending",
          blocks: ["t4"],
          created_at: ts(5),
          updated_at: ts(5),
        },
      ],
      gates: {
        discovery: {
          stage: "discovery",
          status: "pending",
          criteria: [
            { description: "Problem space documented", met: false },
            { description: "Existing solutions catalogued", met: false },
            { description: "Technical feasibility confirmed", met: false },
          ],
        },
      },
      tokens: {
        total_tokens: 1240,
        total_cost: 0.02,
        budget_limit: 5.0,
        budget_used: 0.02,
        budget_remaining: 4.98,
        sessions: [
          {
            worker_id: "w1",
            persona: "researcher",
            model: "claude-sonnet-4-5-20250929",
            input_tokens: 820,
            output_tokens: 420,
            total_tokens: 1240,
            estimated_cost_usd: 0.02,
          },
        ],
      },
      audit: [
        {
          timestamp: ts(5),
          action: "Project initialized",
          actor: "kai",
          category: "stage",
          details: "CLI task manager in Go",
        },
        {
          timestamp: ts(5),
          action: "Stage entered: discovery",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(5),
          action: "Task created: Research CLI task managers",
          actor: "kai",
          category: "task",
          details: "Assigned to researcher persona",
        },
        {
          timestamp: ts(5),
          action: "Task created: Analyze Go CLI frameworks",
          actor: "kai",
          category: "task",
          details: "Blocked by t1",
        },
        {
          timestamp: ts(5),
          action: "Worker spawned: researcher (w1)",
          actor: "kai",
          category: "worker",
          details: "Model: claude-sonnet-4-5, zone: shared",
        },
      ],
      graph: {
        nodes: [
          {
            id: "t1",
            type: "task",
            title: "Research CLI task managers",
            stage: "discovery",
            zone: "shared",
            status: "in_progress",
            persona: "researcher",
            worker_id: "w1",
          },
          {
            id: "t2",
            type: "task",
            title: "Analyze Go CLI frameworks",
            stage: "discovery",
            zone: "shared",
            status: "pending",
            persona: "researcher",
          },
        ],
        edges: [],
        critical_path: ["t1"],
        blocked_count: 0,
        ready_count: 1,
      },
    },
  },
  {
    delay: 1500,
    type: "message",
    role: "assistant",
    content:
      "I've spawned a researcher agent to explore the CLI task manager landscape. Check the Activity tab — every action is logged: who did it, when, and why. The Trace view shows how tasks depend on each other.",
  },

  // --- Worker appears ---
  {
    delay: 2000,
    type: "state",
    patch: {
      workers: [
        {
          id: "w1",
          persona: "researcher",
          zone: "shared",
          status: "busy",
          task: "Research CLI task managers",
          task_id: "t1",
          uptime: 12,
          tokens: 1240,
          model: "claude-sonnet-4-5-20250929",
        },
      ],
      audit: [
        {
          timestamp: ts(5),
          action: "Project initialized",
          actor: "kai",
          category: "stage",
          details: "CLI task manager in Go",
        },
        {
          timestamp: ts(5),
          action: "Stage entered: discovery",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(5),
          action: "Task created: Research CLI task managers",
          actor: "kai",
          category: "task",
          details: "Assigned to researcher persona",
        },
        {
          timestamp: ts(5),
          action: "Task created: Analyze Go CLI frameworks",
          actor: "kai",
          category: "task",
          details: "Blocked by t1",
        },
        {
          timestamp: ts(5),
          action: "Worker spawned: researcher (w1)",
          actor: "kai",
          category: "worker",
          details: "Model: claude-sonnet-4-5, zone: shared",
        },
        {
          timestamp: ts(4),
          action: "Worker w1 picked up task t1",
          actor: "w1:researcher",
          category: "worker",
          details: "Research CLI task managers",
        },
      ],
    },
  },

  // --- Discovery findings ---
  {
    delay: 3500,
    type: "message",
    role: "assistant",
    content:
      "Researcher found 3 popular approaches. Existing tools like Taskwarrior use local file storage, while newer ones use SQLite. For Go, cobra + bubbletea is the dominant stack. All gate criteria met — but I can't advance until you approve. The gate enforces it.",
  },

  // --- Tasks done, gate criteria met ---
  {
    delay: 1500,
    type: "state",
    patch: {
      tasks: [
        {
          id: "t1",
          name: "Research CLI task managers",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "complete",
          worker_id: "w1",
          created_at: ts(5),
          updated_at: ts(3),
        },
        {
          id: "t2",
          name: "Analyze Go CLI frameworks",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "complete",
          worker_id: "w1",
          blocks: ["t4"],
          created_at: ts(5),
          updated_at: ts(3),
        },
      ],
      workers: [
        {
          id: "w1",
          persona: "researcher",
          zone: "shared",
          status: "idle",
          task: "Research CLI task managers",
          task_id: "t1",
          uptime: 45,
          tokens: 3860,
          model: "claude-sonnet-4-5-20250929",
        },
      ],
      gates: {
        discovery: {
          stage: "discovery",
          status: "pending",
          criteria: [
            { description: "Problem space documented", met: true },
            { description: "Existing solutions catalogued", met: true },
            { description: "Technical feasibility confirmed", met: true },
          ],
        },
      },
      tokens: {
        total_tokens: 3860,
        total_cost: 0.06,
        budget_limit: 5.0,
        budget_used: 0.06,
        budget_remaining: 4.94,
        sessions: [
          {
            worker_id: "w1",
            persona: "researcher",
            model: "claude-sonnet-4-5-20250929",
            input_tokens: 2540,
            output_tokens: 1320,
            total_tokens: 3860,
            estimated_cost_usd: 0.06,
          },
        ],
      },
      audit: [
        {
          timestamp: ts(5),
          action: "Project initialized",
          actor: "kai",
          category: "stage",
          details: "CLI task manager in Go",
        },
        {
          timestamp: ts(5),
          action: "Stage entered: discovery",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(5),
          action: "Task created: Research CLI task managers",
          actor: "kai",
          category: "task",
        },
        {
          timestamp: ts(5),
          action: "Task created: Analyze Go CLI frameworks",
          actor: "kai",
          category: "task",
        },
        {
          timestamp: ts(5),
          action: "Worker spawned: researcher (w1)",
          actor: "kai",
          category: "worker",
          details: "Model: claude-sonnet-4-5, zone: shared",
        },
        {
          timestamp: ts(4),
          action: "Worker w1 picked up task t1",
          actor: "w1:researcher",
          category: "worker",
        },
        {
          timestamp: ts(3),
          action: "Task completed: Research CLI task managers",
          actor: "w1:researcher",
          category: "task",
          details: "3 approaches identified, 3860 tokens used",
        },
        {
          timestamp: ts(3),
          action: "Task completed: Analyze Go CLI frameworks",
          actor: "w1:researcher",
          category: "task",
          details: "cobra + bubbletea recommended",
        },
        {
          timestamp: ts(3),
          action: "Gate criteria met: discovery",
          actor: "system",
          category: "gate",
          details: "3/3 criteria satisfied",
        },
      ],
      graph: {
        nodes: [
          {
            id: "t1",
            type: "task",
            title: "Research CLI task managers",
            stage: "discovery",
            zone: "shared",
            status: "complete",
            persona: "researcher",
            worker_id: "w1",
          },
          {
            id: "t2",
            type: "task",
            title: "Analyze Go CLI frameworks",
            stage: "discovery",
            zone: "shared",
            status: "complete",
            persona: "researcher",
            worker_id: "w1",
          },
        ],
        edges: [],
        critical_path: [],
        blocked_count: 0,
        ready_count: 0,
      },
    },
  },

  // --- User approves gate ---
  {
    delay: 2500,
    type: "message",
    role: "user",
    content: "Approve the gate",
  },
  {
    delay: 1000,
    type: "state",
    patch: {
      gates: {
        discovery: {
          stage: "discovery",
          status: "approved",
          criteria: [
            { description: "Problem space documented", met: true },
            { description: "Existing solutions catalogued", met: true },
            { description: "Technical feasibility confirmed", met: true },
          ],
          approved_at: ts(2),
          approval_note: "User approved",
        },
      },
      checkpoints: [
        {
          id: "cp1",
          stage: "discovery",
          created_at: ts(2),
          task_count: 2,
          auto: false,
        },
      ],
      audit: [
        {
          timestamp: ts(5),
          action: "Project initialized",
          actor: "kai",
          category: "stage",
          details: "CLI task manager in Go",
        },
        {
          timestamp: ts(5),
          action: "Stage entered: discovery",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(5),
          action: "Task created: Research CLI task managers",
          actor: "kai",
          category: "task",
        },
        {
          timestamp: ts(5),
          action: "Task created: Analyze Go CLI frameworks",
          actor: "kai",
          category: "task",
        },
        {
          timestamp: ts(5),
          action: "Worker spawned: researcher (w1)",
          actor: "kai",
          category: "worker",
          details: "Model: claude-sonnet-4-5, zone: shared",
        },
        {
          timestamp: ts(4),
          action: "Worker w1 picked up task t1",
          actor: "w1:researcher",
          category: "worker",
        },
        {
          timestamp: ts(3),
          action: "Task completed: Research CLI task managers",
          actor: "w1:researcher",
          category: "task",
          details: "3860 tokens used",
        },
        {
          timestamp: ts(3),
          action: "Task completed: Analyze Go CLI frameworks",
          actor: "w1:researcher",
          category: "task",
        },
        {
          timestamp: ts(3),
          action: "Gate criteria met: discovery",
          actor: "system",
          category: "gate",
          details: "3/3 criteria satisfied",
        },
        {
          timestamp: ts(2),
          action: "Gate approved: discovery",
          actor: "user",
          category: "gate",
          details: "User approved — all criteria verified",
        },
        {
          timestamp: ts(2),
          action: "Checkpoint created: cp1",
          actor: "system",
          category: "checkpoint",
          details: "discovery stage, 2 tasks preserved",
        },
      ],
    },
  },

  // --- Advance to goal ---
  {
    delay: 1500,
    type: "state",
    patch: {
      stage: "goal",
      gates: {
        discovery: {
          stage: "discovery",
          status: "approved",
          criteria: [
            { description: "Problem space documented", met: true },
            { description: "Existing solutions catalogued", met: true },
            { description: "Technical feasibility confirmed", met: true },
          ],
          approved_at: ts(2),
          approval_note: "User approved",
        },
        goal: {
          stage: "goal",
          status: "pending",
          criteria: [
            { description: "Success metrics defined", met: false },
            { description: "Scope boundaries set", met: false },
          ],
        },
      },
    },
  },
  {
    delay: 1000,
    type: "message",
    role: "assistant",
    content:
      "Gate approved — and that approval is in the audit trail forever. Moving to Goal. I need to define what success looks like. What matters most to you — speed, simplicity, or a full feature set?",
  },

  // --- User answers ---
  {
    delay: 3000,
    type: "message",
    role: "user",
    content: "Simplicity — I want something I can actually ship in a weekend",
  },

  // --- Goal tasks + worker ---
  {
    delay: 2000,
    type: "state",
    patch: {
      tasks: [
        {
          id: "t1",
          name: "Research CLI task managers",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "complete",
          worker_id: "w1",
          created_at: ts(5),
          updated_at: ts(3),
        },
        {
          id: "t2",
          name: "Analyze Go CLI frameworks",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "complete",
          worker_id: "w1",
          blocks: ["t4"],
          created_at: ts(5),
          updated_at: ts(3),
        },
        {
          id: "t3",
          name: "Define success criteria",
          stage: "goal",
          zone: "shared",
          persona: "analyst",
          status: "in_progress",
          worker_id: "w2",
          blocks: ["t4", "t5"],
          created_at: ts(2),
          updated_at: ts(2),
        },
      ],
      workers: [
        {
          id: "w1",
          persona: "researcher",
          zone: "shared",
          status: "idle",
          task: "Research CLI task managers",
          task_id: "t1",
          uptime: 45,
          tokens: 3860,
          model: "claude-sonnet-4-5-20250929",
        },
        {
          id: "w2",
          persona: "analyst",
          zone: "shared",
          status: "busy",
          task: "Define success criteria",
          task_id: "t3",
          uptime: 3,
          tokens: 620,
          model: "claude-sonnet-4-5-20250929",
        },
      ],
      graph: {
        nodes: [
          {
            id: "t1",
            type: "task",
            title: "Research CLI task managers",
            stage: "discovery",
            zone: "shared",
            status: "complete",
            persona: "researcher",
            worker_id: "w1",
          },
          {
            id: "t2",
            type: "task",
            title: "Analyze Go CLI frameworks",
            stage: "discovery",
            zone: "shared",
            status: "complete",
            persona: "researcher",
            worker_id: "w1",
          },
          {
            id: "t3",
            type: "task",
            title: "Define success criteria",
            stage: "goal",
            zone: "shared",
            status: "in_progress",
            persona: "analyst",
            worker_id: "w2",
          },
        ],
        edges: [],
        critical_path: ["t3"],
        blocked_count: 0,
        ready_count: 0,
      },
    },
  },
  {
    delay: 2000,
    type: "message",
    role: "assistant",
    content:
      "Perfect. I've scoped the goal: a minimal CLI task manager with add, list, complete, and delete commands. SQLite backend, no TUI — just clean stdout. Shipping in a weekend means cutting the interactive mode.",
  },

  // --- Goal gate met ---
  {
    delay: 2000,
    type: "state",
    patch: {
      tasks: [
        {
          id: "t1",
          name: "Research CLI task managers",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "complete",
          worker_id: "w1",
          created_at: ts(5),
          updated_at: ts(3),
        },
        {
          id: "t2",
          name: "Analyze Go CLI frameworks",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "complete",
          worker_id: "w1",
          blocks: ["t4"],
          created_at: ts(5),
          updated_at: ts(3),
        },
        {
          id: "t3",
          name: "Define success criteria",
          stage: "goal",
          zone: "shared",
          persona: "analyst",
          status: "complete",
          worker_id: "w2",
          blocks: ["t4", "t5"],
          created_at: ts(2),
          updated_at: ts(1),
        },
      ],
      workers: [
        {
          id: "w1",
          persona: "researcher",
          zone: "shared",
          status: "idle",
          task: "Research CLI task managers",
          task_id: "t1",
          uptime: 45,
          tokens: 3860,
          model: "claude-sonnet-4-5-20250929",
        },
        {
          id: "w2",
          persona: "analyst",
          zone: "shared",
          status: "idle",
          task: "Define success criteria",
          task_id: "t3",
          uptime: 18,
          tokens: 2140,
          model: "claude-sonnet-4-5-20250929",
        },
      ],
      gates: {
        discovery: {
          stage: "discovery",
          status: "approved",
          criteria: [
            { description: "Problem space documented", met: true },
            { description: "Existing solutions catalogued", met: true },
            { description: "Technical feasibility confirmed", met: true },
          ],
          approved_at: ts(2),
          approval_note: "User approved",
        },
        goal: {
          stage: "goal",
          status: "approved",
          criteria: [
            { description: "Success metrics defined", met: true },
            { description: "Scope boundaries set", met: true },
          ],
          approved_at: ts(1),
        },
      },
      tokens: {
        total_tokens: 6000,
        total_cost: 0.09,
        budget_limit: 5.0,
        budget_used: 0.09,
        budget_remaining: 4.91,
        sessions: [
          {
            worker_id: "w1",
            persona: "researcher",
            model: "claude-sonnet-4-5-20250929",
            input_tokens: 2540,
            output_tokens: 1320,
            total_tokens: 3860,
            estimated_cost_usd: 0.06,
          },
          {
            worker_id: "w2",
            persona: "analyst",
            model: "claude-sonnet-4-5-20250929",
            input_tokens: 1400,
            output_tokens: 740,
            total_tokens: 2140,
            estimated_cost_usd: 0.03,
          },
        ],
      },
      checkpoints: [
        {
          id: "cp1",
          stage: "discovery",
          created_at: ts(2),
          task_count: 2,
          auto: false,
        },
        {
          id: "cp2",
          stage: "goal",
          created_at: ts(1),
          task_count: 1,
          auto: false,
        },
      ],
      audit: [
        {
          timestamp: ts(5),
          action: "Project initialized",
          actor: "kai",
          category: "stage",
          details: "CLI task manager in Go",
        },
        {
          timestamp: ts(5),
          action: "Stage entered: discovery",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(5),
          action: "Task created: Research CLI task managers",
          actor: "kai",
          category: "task",
        },
        {
          timestamp: ts(5),
          action: "Worker spawned: researcher (w1)",
          actor: "kai",
          category: "worker",
          details: "Model: claude-sonnet-4-5",
        },
        {
          timestamp: ts(4),
          action: "Worker w1 picked up task t1",
          actor: "w1:researcher",
          category: "worker",
        },
        {
          timestamp: ts(3),
          action: "Task completed: Research CLI task managers",
          actor: "w1:researcher",
          category: "task",
          details: "3860 tokens used",
        },
        {
          timestamp: ts(3),
          action: "Task completed: Analyze Go CLI frameworks",
          actor: "w1:researcher",
          category: "task",
        },
        {
          timestamp: ts(3),
          action: "Gate criteria met: discovery (3/3)",
          actor: "system",
          category: "gate",
        },
        {
          timestamp: ts(2),
          action: "Gate approved: discovery",
          actor: "user",
          category: "gate",
          details: "All criteria verified",
        },
        {
          timestamp: ts(2),
          action: "Checkpoint created: cp1",
          actor: "system",
          category: "checkpoint",
          details: "discovery — 2 tasks preserved",
        },
        {
          timestamp: ts(2),
          action: "Stage entered: goal",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(2),
          action: "Worker spawned: analyst (w2)",
          actor: "kai",
          category: "worker",
          details: "Model: claude-sonnet-4-5",
        },
        {
          timestamp: ts(1),
          action: "Task completed: Define success criteria",
          actor: "w2:analyst",
          category: "task",
          details: "Scope: minimal CLI, SQLite, 4 commands",
        },
        {
          timestamp: ts(1),
          action: "Gate criteria met: goal (2/2)",
          actor: "system",
          category: "gate",
        },
        {
          timestamp: ts(1),
          action: "Gate auto-approved: goal",
          actor: "kai",
          category: "gate",
          details: "User preference aligned — shipping in a weekend",
        },
        {
          timestamp: ts(1),
          action: "Checkpoint created: cp2",
          actor: "system",
          category: "checkpoint",
          details: "goal — 1 task preserved",
        },
      ],
    },
  },

  // --- Advance to requirements ---
  {
    delay: 1500,
    type: "state",
    patch: {
      stage: "requirements",
      gates: {
        discovery: {
          stage: "discovery",
          status: "approved",
          criteria: [
            { description: "Problem space documented", met: true },
            { description: "Existing solutions catalogued", met: true },
            { description: "Technical feasibility confirmed", met: true },
          ],
          approved_at: ts(2),
          approval_note: "User approved",
        },
        goal: {
          stage: "goal",
          status: "approved",
          criteria: [
            { description: "Success metrics defined", met: true },
            { description: "Scope boundaries set", met: true },
          ],
          approved_at: ts(1),
        },
        requirements: {
          stage: "requirements",
          status: "pending",
          criteria: [
            { description: "Functional requirements listed", met: false },
            { description: "Data model specified", met: false },
          ],
        },
      },
    },
  },
  {
    delay: 1500,
    type: "message",
    role: "assistant",
    content:
      "Now in Requirements. Every task traces back to a stage. Every stage has criteria that must be met before advancing. Check the Activity tab — nothing happens in DutyBound without a paper trail.",
  },

  // --- Requirements work with dependencies ---
  {
    delay: 2500,
    type: "state",
    patch: {
      tasks: [
        {
          id: "t1",
          name: "Research CLI task managers",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "complete",
          worker_id: "w1",
          created_at: ts(5),
          updated_at: ts(3),
        },
        {
          id: "t2",
          name: "Analyze Go CLI frameworks",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "complete",
          worker_id: "w1",
          blocks: ["t4"],
          created_at: ts(5),
          updated_at: ts(3),
        },
        {
          id: "t3",
          name: "Define success criteria",
          stage: "goal",
          zone: "shared",
          persona: "analyst",
          status: "complete",
          worker_id: "w2",
          blocks: ["t4", "t5"],
          created_at: ts(2),
          updated_at: ts(1),
        },
        {
          id: "t4",
          name: "Draft functional requirements",
          stage: "requirements",
          zone: "backend",
          persona: "specs",
          status: "in_progress",
          worker_id: "w3",
          blocked_by: ["t2", "t3"],
          blocks: ["t5", "t6"],
          created_at: ts(1),
          updated_at: ts(1),
        },
        {
          id: "t5",
          name: "Define data model",
          stage: "requirements",
          zone: "database",
          persona: "specs",
          status: "blocked",
          blocked_by: ["t3", "t4"],
          blocks: ["t6"],
          created_at: ts(1),
          updated_at: ts(1),
        },
      ],
      workers: [
        {
          id: "w1",
          persona: "researcher",
          zone: "shared",
          status: "idle",
          task: "Research CLI task managers",
          task_id: "t1",
          uptime: 45,
          tokens: 3860,
          model: "claude-sonnet-4-5-20250929",
        },
        {
          id: "w2",
          persona: "analyst",
          zone: "shared",
          status: "idle",
          task: "Define success criteria",
          task_id: "t3",
          uptime: 18,
          tokens: 2140,
          model: "claude-sonnet-4-5-20250929",
        },
        {
          id: "w3",
          persona: "specs",
          zone: "backend",
          status: "busy",
          task: "Draft functional requirements",
          task_id: "t4",
          uptime: 5,
          tokens: 890,
          model: "claude-sonnet-4-5-20250929",
        },
      ],
      graph: {
        nodes: [
          {
            id: "t1",
            type: "task",
            title: "Research CLI task managers",
            stage: "discovery",
            zone: "shared",
            status: "complete",
            persona: "researcher",
            worker_id: "w1",
          },
          {
            id: "t2",
            type: "task",
            title: "Analyze Go CLI frameworks",
            stage: "discovery",
            zone: "shared",
            status: "complete",
            persona: "researcher",
            worker_id: "w1",
          },
          {
            id: "t3",
            type: "task",
            title: "Define success criteria",
            stage: "goal",
            zone: "shared",
            status: "complete",
            persona: "analyst",
            worker_id: "w2",
          },
          {
            id: "t4",
            type: "task",
            title: "Draft functional requirements",
            stage: "requirements",
            zone: "backend",
            status: "in_progress",
            persona: "specs",
            worker_id: "w3",
          },
          {
            id: "t5",
            type: "task",
            title: "Define data model",
            stage: "requirements",
            zone: "database",
            status: "blocked",
            persona: "specs",
          },
        ],
        edges: [
          { source: "t2", target: "t4", type: "blocks" },
          { source: "t3", target: "t4", type: "blocks" },
          { source: "t3", target: "t5", type: "blocks" },
          { source: "t4", target: "t5", type: "blocks" },
          { source: "t4", target: "t6", type: "blocks" },
          { source: "t5", target: "t6", type: "blocks" },
        ],
        critical_path: ["t4", "t5", "t6"],
        blocked_count: 1,
        ready_count: 0,
      },
      audit: [
        {
          timestamp: ts(5),
          action: "Project initialized",
          actor: "kai",
          category: "stage",
          details: "CLI task manager in Go",
        },
        {
          timestamp: ts(5),
          action: "Stage entered: discovery",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(5),
          action: "Worker spawned: researcher (w1)",
          actor: "kai",
          category: "worker",
        },
        {
          timestamp: ts(3),
          action: "Task completed: Research CLI task managers",
          actor: "w1:researcher",
          category: "task",
        },
        {
          timestamp: ts(3),
          action: "Task completed: Analyze Go CLI frameworks",
          actor: "w1:researcher",
          category: "task",
        },
        {
          timestamp: ts(3),
          action: "Gate criteria met: discovery (3/3)",
          actor: "system",
          category: "gate",
        },
        {
          timestamp: ts(2),
          action: "Gate approved: discovery",
          actor: "user",
          category: "gate",
        },
        {
          timestamp: ts(2),
          action: "Checkpoint created: cp1",
          actor: "system",
          category: "checkpoint",
          details: "discovery — 2 tasks",
        },
        {
          timestamp: ts(2),
          action: "Stage entered: goal",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(2),
          action: "Worker spawned: analyst (w2)",
          actor: "kai",
          category: "worker",
        },
        {
          timestamp: ts(1),
          action: "Task completed: Define success criteria",
          actor: "w2:analyst",
          category: "task",
        },
        {
          timestamp: ts(1),
          action: "Gate approved: goal",
          actor: "kai",
          category: "gate",
        },
        {
          timestamp: ts(1),
          action: "Checkpoint created: cp2",
          actor: "system",
          category: "checkpoint",
          details: "goal — 1 task",
        },
        {
          timestamp: ts(1),
          action: "Stage entered: requirements",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(1),
          action: "Worker spawned: specs (w3)",
          actor: "kai",
          category: "worker",
          details: "Model: claude-sonnet-4-5, zone: backend",
        },
        {
          timestamp: ts(1),
          action: "Task created: Draft functional requirements",
          actor: "kai",
          category: "task",
          details: "Depends on t2, t3 — blocks t5, t6",
        },
        {
          timestamp: ts(1),
          action: "Task created: Define data model",
          actor: "kai",
          category: "task",
          details: "Blocked by t3, t4 — blocks t6",
        },
      ],
    },
  },
  {
    delay: 3000,
    type: "message",
    role: "assistant",
    content:
      'Check the Trace view — "Define data model" is blocked until requirements are drafted. The critical path runs through t4 → t5 → t6. DutyBound enforces this: no worker can start a blocked task. No agent can skip the rules.',
  },

  // --- Requirements complete, advance to planning ---
  {
    delay: 2000,
    type: "state",
    patch: {
      stage: "planning",
      tasks: [
        {
          id: "t1",
          name: "Research CLI task managers",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "complete",
          worker_id: "w1",
          created_at: ts(5),
          updated_at: ts(3),
        },
        {
          id: "t2",
          name: "Analyze Go CLI frameworks",
          stage: "discovery",
          zone: "shared",
          persona: "researcher",
          status: "complete",
          worker_id: "w1",
          blocks: ["t4"],
          created_at: ts(5),
          updated_at: ts(3),
        },
        {
          id: "t3",
          name: "Define success criteria",
          stage: "goal",
          zone: "shared",
          persona: "analyst",
          status: "complete",
          worker_id: "w2",
          blocks: ["t4", "t5"],
          created_at: ts(2),
          updated_at: ts(1),
        },
        {
          id: "t4",
          name: "Draft functional requirements",
          stage: "requirements",
          zone: "backend",
          persona: "specs",
          status: "complete",
          worker_id: "w3",
          blocked_by: ["t2", "t3"],
          blocks: ["t5", "t6"],
          created_at: ts(1),
          updated_at: ts(0.5),
        },
        {
          id: "t5",
          name: "Define data model",
          stage: "requirements",
          zone: "database",
          persona: "specs",
          status: "complete",
          worker_id: "w3",
          blocked_by: ["t3", "t4"],
          blocks: ["t6"],
          created_at: ts(1),
          updated_at: ts(0.5),
        },
        {
          id: "t6",
          name: "Create implementation plan",
          stage: "planning",
          zone: "shared",
          persona: "architect",
          status: "in_progress",
          worker_id: "w4",
          blocked_by: ["t4", "t5"],
          created_at: ts(0.5),
          updated_at: ts(0.5),
        },
      ],
      workers: [
        {
          id: "w1",
          persona: "researcher",
          zone: "shared",
          status: "idle",
          task: "Research CLI task managers",
          task_id: "t1",
          uptime: 45,
          tokens: 3860,
          model: "claude-sonnet-4-5-20250929",
        },
        {
          id: "w2",
          persona: "analyst",
          zone: "shared",
          status: "idle",
          task: "Define success criteria",
          task_id: "t3",
          uptime: 18,
          tokens: 2140,
          model: "claude-sonnet-4-5-20250929",
        },
        {
          id: "w3",
          persona: "specs",
          zone: "backend",
          status: "idle",
          task: "Define data model",
          task_id: "t5",
          uptime: 32,
          tokens: 4210,
          model: "claude-sonnet-4-5-20250929",
        },
        {
          id: "w4",
          persona: "architect",
          zone: "shared",
          status: "busy",
          task: "Create implementation plan",
          task_id: "t6",
          uptime: 2,
          tokens: 450,
          model: "claude-sonnet-4-5-20250929",
        },
      ],
      gates: {
        discovery: {
          stage: "discovery",
          status: "approved",
          criteria: [
            { description: "Problem space documented", met: true },
            { description: "Existing solutions catalogued", met: true },
            { description: "Technical feasibility confirmed", met: true },
          ],
          approved_at: ts(2),
          approval_note: "User approved",
        },
        goal: {
          stage: "goal",
          status: "approved",
          criteria: [
            { description: "Success metrics defined", met: true },
            { description: "Scope boundaries set", met: true },
          ],
          approved_at: ts(1),
        },
        requirements: {
          stage: "requirements",
          status: "approved",
          criteria: [
            { description: "Functional requirements listed", met: true },
            { description: "Data model specified", met: true },
          ],
          approved_at: ts(0.5),
        },
        planning: {
          stage: "planning",
          status: "pending",
          criteria: [
            { description: "Task breakdown created", met: false },
            { description: "Dependencies mapped", met: false },
          ],
        },
      },
      tokens: {
        total_tokens: 11460,
        total_cost: 0.17,
        budget_limit: 5.0,
        budget_used: 0.17,
        budget_remaining: 4.83,
        sessions: [
          {
            worker_id: "w1",
            persona: "researcher",
            model: "claude-sonnet-4-5-20250929",
            input_tokens: 2540,
            output_tokens: 1320,
            total_tokens: 3860,
            estimated_cost_usd: 0.06,
          },
          {
            worker_id: "w2",
            persona: "analyst",
            model: "claude-sonnet-4-5-20250929",
            input_tokens: 1400,
            output_tokens: 740,
            total_tokens: 2140,
            estimated_cost_usd: 0.03,
          },
          {
            worker_id: "w3",
            persona: "specs",
            model: "claude-sonnet-4-5-20250929",
            input_tokens: 2800,
            output_tokens: 1410,
            total_tokens: 4210,
            estimated_cost_usd: 0.06,
          },
          {
            worker_id: "w4",
            persona: "architect",
            model: "claude-sonnet-4-5-20250929",
            input_tokens: 300,
            output_tokens: 150,
            total_tokens: 450,
            estimated_cost_usd: 0.01,
          },
        ],
      },
      checkpoints: [
        {
          id: "cp1",
          stage: "discovery",
          created_at: ts(2),
          task_count: 2,
          auto: false,
        },
        {
          id: "cp2",
          stage: "goal",
          created_at: ts(1),
          task_count: 1,
          auto: false,
        },
        {
          id: "cp3",
          stage: "requirements",
          created_at: ts(0.5),
          task_count: 2,
          auto: true,
        },
      ],
      graph: {
        nodes: [
          {
            id: "t1",
            type: "task",
            title: "Research CLI task managers",
            stage: "discovery",
            zone: "shared",
            status: "complete",
            persona: "researcher",
            worker_id: "w1",
          },
          {
            id: "t2",
            type: "task",
            title: "Analyze Go CLI frameworks",
            stage: "discovery",
            zone: "shared",
            status: "complete",
            persona: "researcher",
            worker_id: "w1",
          },
          {
            id: "t3",
            type: "task",
            title: "Define success criteria",
            stage: "goal",
            zone: "shared",
            status: "complete",
            persona: "analyst",
            worker_id: "w2",
          },
          {
            id: "t4",
            type: "task",
            title: "Draft functional requirements",
            stage: "requirements",
            zone: "backend",
            status: "complete",
            persona: "specs",
            worker_id: "w3",
          },
          {
            id: "t5",
            type: "task",
            title: "Define data model",
            stage: "requirements",
            zone: "database",
            status: "complete",
            persona: "specs",
            worker_id: "w3",
          },
          {
            id: "t6",
            type: "task",
            title: "Create implementation plan",
            stage: "planning",
            zone: "shared",
            status: "in_progress",
            persona: "architect",
            worker_id: "w4",
          },
        ],
        edges: [
          { source: "t2", target: "t4", type: "blocks" },
          { source: "t3", target: "t4", type: "blocks" },
          { source: "t3", target: "t5", type: "blocks" },
          { source: "t4", target: "t5", type: "blocks" },
          { source: "t4", target: "t6", type: "blocks" },
          { source: "t5", target: "t6", type: "blocks" },
        ],
        critical_path: ["t4", "t5", "t6"],
        blocked_count: 0,
        ready_count: 0,
      },
      audit: [
        {
          timestamp: ts(5),
          action: "Project initialized",
          actor: "kai",
          category: "stage",
          details: "CLI task manager in Go",
        },
        {
          timestamp: ts(5),
          action: "Stage entered: discovery",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(5),
          action: "Worker spawned: researcher (w1)",
          actor: "kai",
          category: "worker",
        },
        {
          timestamp: ts(3),
          action: "Task completed: Research CLI task managers",
          actor: "w1:researcher",
          category: "task",
        },
        {
          timestamp: ts(3),
          action: "Task completed: Analyze Go CLI frameworks",
          actor: "w1:researcher",
          category: "task",
        },
        {
          timestamp: ts(2),
          action: "Gate approved: discovery",
          actor: "user",
          category: "gate",
        },
        {
          timestamp: ts(2),
          action: "Checkpoint created: cp1",
          actor: "system",
          category: "checkpoint",
        },
        {
          timestamp: ts(2),
          action: "Stage entered: goal",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(2),
          action: "Worker spawned: analyst (w2)",
          actor: "kai",
          category: "worker",
        },
        {
          timestamp: ts(1),
          action: "Task completed: Define success criteria",
          actor: "w2:analyst",
          category: "task",
        },
        {
          timestamp: ts(1),
          action: "Gate approved: goal",
          actor: "kai",
          category: "gate",
        },
        {
          timestamp: ts(1),
          action: "Checkpoint created: cp2",
          actor: "system",
          category: "checkpoint",
        },
        {
          timestamp: ts(1),
          action: "Stage entered: requirements",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(1),
          action: "Worker spawned: specs (w3)",
          actor: "kai",
          category: "worker",
        },
        {
          timestamp: ts(0.5),
          action: "Task completed: Draft functional requirements",
          actor: "w3:specs",
          category: "task",
        },
        {
          timestamp: ts(0.5),
          action: "Dependency unblocked: t5 (Define data model)",
          actor: "system",
          category: "task",
          details: "Blocker t4 completed",
        },
        {
          timestamp: ts(0.5),
          action: "Task completed: Define data model",
          actor: "w3:specs",
          category: "task",
        },
        {
          timestamp: ts(0.5),
          action: "Gate approved: requirements",
          actor: "kai",
          category: "gate",
          details: "Auto-approved — all criteria met",
        },
        {
          timestamp: ts(0.5),
          action: "Checkpoint created: cp3",
          actor: "system",
          category: "checkpoint",
          details: "Auto-checkpoint at stage transition",
        },
        {
          timestamp: ts(0.5),
          action: "Stage entered: planning",
          actor: "kai",
          category: "stage",
        },
        {
          timestamp: ts(0.5),
          action: "Worker spawned: architect (w4)",
          actor: "kai",
          category: "worker",
          details: "Model: claude-sonnet-4-5, zone: shared",
        },
      ],
    },
  },
  {
    delay: 1500,
    type: "message",
    role: "assistant",
    content:
      "Now in Planning. The architect is mapping out the implementation. Look at the Activity view — every stage transition, gate approval, dependency unblock, and checkpoint is in the audit trail. Full provenance: you always know who did what and why.",
  },

  // --- Final message ---
  {
    delay: 4000,
    type: "message",
    role: "assistant",
    content:
      "That's DutyBound. Every commit traces back to a task. Every task traces back to a stage. Quality gates prevent premature advancement. The dependency graph enforces ordering. And the audit trail gives you complete provenance over every decision an AI agent makes. No agent can skip the rules — not even the orchestrator. Want to try it yourself?",
  },
];

export { INITIAL_STATE };
